services:
  redis:
    image: redis:7
    container_name: redis_server
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env.prod
    restart: on-failure
  bot:
    build: ./src/bot
    container_name: bot_server
    command: [ "/app/scripts/bot.sh" ]
    env_file:
      - .env.prod
  client:
    build: ./src/client
    container_name: client_server
    command: [ "/app/scripts/client.sh" ]
    env_file:
      - .env.prod