version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis_server
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env.prod
    restart: on-failure
    volumes:
      - redis-data:/data
  bot:
    build: .
    container_name: bot_server
    command: [ "/app/scripts/bot.sh" ]
    env_file:
      - .env.prod
  client:
    build: .
    container_name: client_server
    command: [ "/app/scripts/client.sh" ]
    env_file:
      - .env.prod

volumes:
  redis-data:
    driver: local